#+title: Lacerta
#+subtitle: Lacerta parses WhatsApp exported logs
#+export_file_name: index
#+setupfile: ~/.emacs.d/org-templates/projects.org

| Website         | https://andinus.nand.sh/lacerta             |
| Source          | https://git.tilde.institute/andinus/lacerta |
| GitHub (mirror) | https://github.com/andinus/lacerta          |

* Installation

Lacerta is released to ~fez~, you can get it from there or install it from
source. In any case, ~zef~ is required to install the distribution.

You can run Lacerta without ~zef~. Just run ~raku -Ilib bin/lacerta~ from
within the source directory.

** Release

1. Run ~zef install lacerta~.

Lacerta should be installed, try running ~lacerta --version~ to confirm.

** From Source

You can either download the release archive generated by cgit/GitHub or
clone the project if you have ~git~ installed.

*** Without ~git~

1. Download the release:
   - https://git.tilde.institute/andinus/lacerta
   - https://github.com/andinus/lacerta/releases
2. Extract the file.
3. Run ~zef install .~ in source directory.

*** With ~git~

All commits will be signed by my [[https://andinus.nand.sh/static/D9AE4AEEE1F1B3598E81D9DFB67D55D482A799FD.asc][PGP Key]].

#+begin_src sh
# Clone the project.
git clone https://git.tilde.institute/andinus/lacerta
cd lacerta

# Install lacerta.
zef install .
#+end_src

* Documentation

** Implementation

It reads the log line by line and tries to match it with ~WhatsApp~
grammar.

** Options

*** input

Exported WhatsApp log.

*** profile-name

Your WhatsApp profile name. This is required to get stats for /Left/ and
/Deleted/ column.

** Caveats

/Words/ count can be less than the actual count. If the message contains
new lines then they have them in the log too. We read the log line by
line, so it'll miss parts of messages with newline in them.

* News

** v0.1.0 - 2021-07-29

Initial Implementation.
